# Generated by Django 5.0.7 on 2024-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to='./uploads/products/images/', verbose_name='product_image'),
        ),
    ]
