# Generated by Django 5.0.7 on 2024-07-30 03:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.image_upload_path, verbose_name='image'),
        ),
    ]
